# Generated by Django 2.2.6 on 2019-11-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0002_auto_20191101_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='tag_id_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='tag_id_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='tag_id_3',
            field=models.IntegerField(default=0),
        ),
    ]
