# Generated by Django 2.2.6 on 2019-11-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_auto_20191102_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='tags',
        ),
    ]
