# Generated by Django 2.2.6 on 2019-11-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0006_auto_20191107_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='about',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='like_sum',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='restriction',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='title',
        ),
        migrations.AddField(
            model_name='competition',
            name='theme',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
