# Generated by Django 2.2.6 on 2019-11-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0007_auto_20191111_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='user_id',
        ),
        migrations.AddField(
            model_name='competition',
            name='hashtag',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
