# Generated by Django 2.0.7 on 2019-12-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0008_auto_20191111_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='theme',
        ),
        migrations.AddField(
            model_name='competition',
            name='img',
            field=models.ImageField(default='defo', upload_to='documents/'),
        ),
    ]
