# Generated by Django 2.0.7 on 2019-12-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0009_auto_20191206_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='title',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='competition',
            name='img',
            field=models.ImageField(default='defo', upload_to=''),
        ),
    ]
