# Generated by Django 2.0.7 on 2019-12-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0010_auto_20191206_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='hashtag',
            new_name='theme',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='participate_sum',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='title',
        ),
    ]
