# Generated by Django 3.0 on 2019-12-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0011_auto_20191206_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
