# Generated by Django 3.0 on 2019-12-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0012_competition_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='img',
            field=models.ImageField(default='defo', upload_to='img/%Y%m%d'),
        ),
    ]
